import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { parse } from 'yaml';
import { parseModel, validateModel, render, jsonSchema, themes } from '../src/engine.ts';
import { matrixMarkdown, reviewCsv } from '../src/report.ts';
import { escapeXml, wrap } from '../src/svg.ts';
const source = await readFile(new URL('../examples/obcm.yaml', import.meta.url), 'utf8');
const signals = await readFile(new URL('../examples/signal-loop.yaml', import.meta.url), 'utf8');
const fresh = () => parse(source);
const model = parseModel(source);
const mode = (id: string) => model.modes.find(m => m.id === id)!;

test('resolves five modes without mutating the source', () => { assert.equal(model.modes.length, 5); const raw = fresh(); validateModel(raw); assert.equal(raw.modes[1].extends, 'charging'); });
test('P and Q are V2G-only in the supplied example', () => { assert(!mode('charging').controls.inverter.some(a => a.quantity === 'q')); assert(mode('v2g').controls.inverter.some(a => a.quantity === 'q')); assert(mode('v2g').controls.cllc.some(a => a.quantity === 'p')); });
test('preserves unspecified roles instead of inventing cascade topology', () => { assert.equal(mode('v2l').controls.inverter.find(a => a.quantity === 'iac')?.role, 'unspecified'); });
test('V2H inheritance does not introduce reverse absorption', () => { assert.equal(mode('v2h').flow.ac_inv, 'reverse'); assert.match(mode('v2h').note!, /not inferred/); });
test('child assignment lists replace, including explicit empty lists', () => { const m = fresh(); m.modes[1].controls.inverter = []; assert.deepEqual(validateModel(m).modes[1].controls.inverter, []); });
test('rejects duplicate ids', () => { const m = fresh(); m.stages[1].id = m.stages[0].id; assert.throws(() => validateModel(m), /Duplicate/); });
test('rejects unknown keys', () => { assert.throws(() => validateModel({ ...fresh(), typo: true }), /Unrecognized/); });
test('rejects invalid references', () => { const m = fresh(); m.modes[0].controls.inverter[0].quantity = 'missing'; assert.throws(() => validateModel(m), /Unknown quantity/); });
test('rejects unknown control stages', () => { const m = fresh(); m.modes[0].controls.missing = []; assert.throws(() => validateModel(m), /Unknown control stage/); });
test('rejects unknown groups', () => { const m = fresh(); m.modes[0].group = 'missing'; assert.throws(() => validateModel(m), /Unknown group/); });
test('rejects inheritance cycles', () => { const m = fresh(); m.modes[0].extends = 'v2g'; assert.throws(() => validateModel(m), /cycle/); });
test('rejects unknown parents', () => { const m = fresh(); m.modes[1].extends = 'missing'; assert.throws(() => validateModel(m), /Unknown parent/); });
test('rejects conflicting exclusive regulators', () => { const m = fresh(); m.modes[0].controls.cllc.push({ quantity: 'vdc', role: 'regulator' }); assert.throws(() => validateModel(m), /Multiple exclusive regulators/); });
test('rejects reverse flow on forward-only hardware', () => { const m = fresh(); m.links[0].capability = 'forward'; assert.throws(() => validateModel(m), /reverse flow/); });
test('rejects missing flows and unknown link ids', () => { const m = fresh(); delete m.modes[0].flow.ac_inv; assert.throws(() => validateModel(m), /Missing flow/); m.modes[0].flow.typo = 'forward'; assert.throws(() => validateModel(m), /Unknown power link/); });
test('requires contiguous physical boundaries and serial stage links', () => { const m = fresh(); m.boundary.members = ['ac', 'cllc']; assert.throws(() => validateModel(m), /contiguous/); const other = fresh(); other.links[0].to = 'battery'; assert.throws(() => validateModel(other), /stages order/); });
test('rejects duplicate YAML keys and oversized input', () => { assert.throws(() => parseModel(source + '\ntitle: Duplicate\n'), /unique|already|duplicate/i); assert.throws(() => parseModel('x'.repeat(131073)), /128 KiB/); });
test('rejects unknown signal ports', () => { const m = parse(signals); m.signals.edges[0].to.port = 'missing'; assert.throws(() => validateModel(m), /Unknown port/); });
test('SVG escapes all XML-sensitive text', async () => { const m = fresh(); m.title = '<script>alert("x")</script>'; const d = await render(validateModel(m)); assert(!d.svg.includes('<script>')); assert(d.svg.includes('&lt;script&gt;')); assert.equal(escapeXml('a&b'), 'a&amp;b'); });
test('renders every curated view and theme deterministically', async () => { for (const theme of Object.keys(themes) as (keyof typeof themes)[]) for (const view of ['overview', 'matrix', 'topology', 'mode'] as const) { const a = await render(model, { theme, view, mode: 'v2g' }); const b = await render(model, { theme, view, mode: 'v2g' }); assert.equal(a.svg, b.svg); assert(!/NaN|undefined/.test(a.svg)); assert(a.width > 0 && a.height > 0); assert(!a.svg.includes('foreignObject')); } });
test('renders an ELK graph deterministically', async () => { const m = parseModel(signals); const a = await render(m, { view: 'signals' }); const b = await render(m, { view: 'signals' }); assert.equal(a.svg, b.svg); assert.match(a.svg, /marker-end="url\(#signal-arrow\)"/); });
test('unknown mode and unavailable graph fail explicitly', async () => { await assert.rejects(render(model, { view: 'mode', mode: 'bad' }), /Unknown mode/); await assert.rejects(render(model, { view: 'signals' }), /no signal graph/i); });
test('CJK and long words wrap without dropping characters', () => { assert.equal(wrap('가나다라마바사', 35, 16).join(''), '가나다라마바사'); assert.equal(wrap('averylongwordwithoutspaces', 30, 16).join(''), 'averylongwordwithoutspaces'); });
test('reports are derived from the same assignments and do not claim test success', () => { assert.match(matrixMarkdown(model), /V2G-AC/); assert.match(reviewCsv(model), /NOT_REVIEWED/); assert(!reviewCsv(model).includes('PASS')); const m = structuredClone(model); m.modes[0].label = '=1+1'; assert(reviewCsv(m).includes("'=1+1")); });
test('schema is generated from the runtime schema', () => { const schema = jsonSchema(); assert.equal(schema.type, 'object'); assert.equal(schema.additionalProperties, false); assert(schema.properties?.schemaVersion); });
test('CLI generates assets and returns a failing exit code for invalid selection', async () => { const out = await mkdtemp(join(tmpdir(), 'control-render-')); try { const run = promisify(execFile); await run(process.execPath, ['--experimental-strip-types', 'src/cli.ts', '--out', out, '--view', 'overview']); assert.match(await readFile(join(out, 'overview.svg'), 'utf8'), /<svg/); await assert.rejects(run(process.execPath, ['--experimental-strip-types', 'src/cli.ts', '--view', 'not-a-view'])); } finally { await rm(out, { recursive: true, force: true }); } });
